const itemList = [
    'Amazon Armor',
    'Amazon Helmet',
    'Amazon Shield',
    'Ball Gown',
    'Blessed Shield',
    'Blue Sphere',
    'Blue Tome',
    /* 'Broken Amulet', */
    'Bronze Necklace',
    /* 'Bunnyslippers', */
    "Chayenne's Magical Key",
    'Cobra Axe',
    'Cobra Boots',
    'Cobra Crossbow',
    'Cobra Hood',
    'Cobra Rod',
    'Cobra Wand',
    'Crackling Egg',
    'Dark Trinity Mace',
    'Deepling Fork',
    'Dwarven Armor',
    'Elemental Spikes',
    'Eye of the Storm',
    'Falcon Coif',
    'Falcon Greaves',
    "Ferumbras' Hat",
    'Gamemaster Doll',
    'Golden Crown',
    'Golden Helmet',
    'Golden Rune',
    'Green Tome',
    'Grey Tome',
    'Hammer of Prophecy',
    'Horned Helmet',
    'Key to Knowledge',
    'Magic Longsword',
    'Menacing Egg',
    'Mysterious Scroll',
    'Pair of Soulstalkers',
    'Pair of Soulwalkers',
    'Rose Shield',
    'Shield of Honour',
    'Solar Axe',
    'Soulbastion',
    'Soulbiter',
    'Soulbleeder',
    'Soulcrusher',
    'Soulcutter',
    /* 'Souleater', */
    'Soulhexer',
    'Soulmaimer',
    'Soulmantle',
    'Soulpiercer',
    'Soulshanks',
    'Soulshell',
    'Soulshredder',
    'Soulshroud',
    'Soulstrider',
    'Soultainter',
    'Spectral Saddle',
    'The Devileye',
    'The Epiphany',
    'Thunder Hammer',
    'Warlord Sword',
    /* 'Winged Helmet', */
    /* 'Yellow Rose' */
]

module.exports = { itemList }