const quests = {
    "Honorary Barbarian": "Barbarian Test",
    "Lion's Den Explorer": "Lion's Rock",
    "The Shattered Isles": "The Shattered Isles",
    "Twenty Miles Beneath The Sea": "Twenty Miles Beneath the Sea",
    "Blood Brothers": "Blood Brothers",
    "The Ice Islands": "The Ice Islands",
    "The New Frontier": "The New Frontier",
    "Wrath of the Emperor": "Wrath of the Emperor",
    "The Ape City": "The Ape City",
    "The Pits of Inferno": "The Pits of Inferno",
    "The Inquisition": "The Inquisition",
    "Rathleton Citizen": "Rathleton (Citzen)",
    "Hero of Rathleton": "Hero of Rathleton",
    "Lost Palace Raider": "Asura Palace",
    "Corruption Contained": "Cults of Tibia",
    "Dark Trails": "Dark Trails",
    "Drama in Darama": "Grimvale",
    "Dream Catcher": "The Dream Courts",
    "Heart of Destruction": "Heart of Destruction",
    "Over the Moon": "The Curse Spreads",
    "Sun and Sea": "Kilmaresh",
    Beyonder: "Feaster of Souls",
    "Library Liberator": "The Secret Library",
    "Ferumbras' Ascendant": "Ferumbras' Ascendant",
    "A Study in Scarlett": "The Order of the Cobra",
    "Millennial Falcon": "The Order of the Falcon",
    Lionheart: "The Order of the Lion",
    "Honorary Gnome": "Bigfoot's Burden (Rank IV)",
    "Gnomish Art of War": "Bigfoot's Burden (Free boss access)",
    "Buried the Baron": "Dangerous Depths (Warzone 4)",
    "His Days are Counted": "Dangerous Depths (Warzone 5)",
    "Duked it Out": "Dangerous Depths (Warzone 6)",
    "Soul War": "Soul War",
    "The Postman Missions": "The Postman Missions",
    "The Djinn War - Marid Faction": "The Djinn War (green)",
    "The Djinn War - Efreet Faction": "The Djinn War (blue)",
    "Recognised Trader": "The Travelling Trader (Rashid)",
    "The Thieves Guild": "The Thieves Guild",
    "The Explorer Society": "The Explorer Society",
    "Shadows of Yalahar": "Shadows of Yalahar"
}

const outfits = {
    Alumni: "Mage",
    "Mystic Fabric Magic": "Elementalist",
    "Inquisition's Arm": "Hand of the Inquisition",
    "Exemplary Citizen": "Citzen",
    "Hunting with Style": "Hunter",
    "In Shining Armor": "Knight",
    "Of Wolves and Bears": "Druid",
    "Bane of the Hive": "Insectoid",
    "Exalted Battle Mage": "Battle Mage",
    Aristocrat: "Nobleman",
    "Beak Doctor": "Afflicted",
    "Brutal Politeness": "Barbarian",
    "Cave Completionist": "Cave Explorer",
    "Citizen of Issavi": "Citzen of Issavi",
    "Cobbled and Patched": "Makeshift Warrior",
    "Crystal Clear": "Crystal Warlord",
    Demonbane: "Demon Hunter",
    "Dream Warden": "Dream Warden",
    "Dream Warrior": "Dream Warrior",
    Falconer: "Falconer",
    "Fool at Heart": "Jester",
    Funghitastic: "Soil Guardian",
    "Glooth Engineer": "Glooth Engineer",
    "Honorary Rascoohan": "Rascoohan",
    "Life on the Streets": "Beggar",
    "Mainstreet Nightmare": "Poltergeist",
    "Master of War": "Warmaster",
    "Nightmare Walker": "Nightmare",
    "One Thousand and One": "Oriental",
    "Out in the Snowstorm": "Norseman",
    Peazzekeeper: "Wayfarer",
    "Raider in the Dark": "Percht Raider",
    "Reason to Celebrate": "Festive",
    "Rift Warrior": "Rift Warrior",
    Ritualist: "Summoner",
    "Skull and Bones": "Brotherhood of Bones",
    "Spolium Profundis": "Deepling",
    Swashbuckler: "Pirate",
    "Swift Death": "Assassin",
    Traditionalist: "Orcsoberfest Garb",
    "True Dedication": "Demon",
    "Unleash the Beast": "Revenant",
    Warlock: "Wizard",
    "Way of the Shaman": "Shaman",
    "Widely Travelled": "Discoverer",
    "Wild Warrior": "Warrior",
}

const mounts = {
    Bearbaiting: "War Bear",
    "Beneath the Sea": "Manta Ray",
    Bibliomaniac: "Fleeting Knowledge",
    Blacknailed: "Hellgrip",
    "Chequered Teddy": "Tamed Panda",
    "Dragon Mimicry": "Dragonling",
    "Do a Barrel Roll!": "Rolling Barrel",
    "Fabled Construction": "Glooth Glider",
    "Fata Morgana": "Dromedary",
    "Fried Shrimp": "Titanica",
    "Friend of Elves": "Kingly Deer",
    "Gear Up": "Walker",
    "Golden Sands": "Scorpion King",
    "Gryphon Rider": "Gryphon",
    "Hot on the Trail": "Singeing Steed",
    "Icy Glare": "Ursagrodon",
    "Knock on Wood": "Tin Lizzard",
    "Lacewing Catcher": "Lacewing Moth",
    "Lion King": "Noble Lion",
    "Little Ball of Wool": "Black Sheep",
    "Lovely Dots": "Ladybug",
    "Loyal Lad": "Donkey",
    "Lucky Horseshoe": "War Horse",
    "Luminous Kitty": "Blazebringer",
    Magnetised: "Ironblight",
    "Mind the Dog!": "Gnarlhound",
    "Moth Whisperer": "Hibernal Moth",
    "No Horse Open Sleigh": "Bright Percht Sleigh",
    "Nothing but Hot Air": "Haze",
    "Out of the Stone Age": "Undead Cavebear",
    "Pecking Order": "Racing Bird",
    "Personal Nightmare": "Shock Head",
    "Phantastic!": "Phant",
    "Pig-Headed": "Rapid Boar",
    "Release the Kraken": "Krakoloss",
    "Rhino Rider": "Stone Rhino",
    "Running the Rift": "Rift Runner",
    "Scales and Tail": "Draptor",
    "Shell we take a Ride": "Shellodon",
    "Slugging Around": "Tiger Slug",
    "Spin-Off": "Widow Queen",
    "Starless Night": "Midnight Panther",
    "Steppe Elegance": "Antelope",
    Stuntman: "Uniwheel",
    "Swamp Beast": "Water Buffalo",
    "The Right Tone": "Crystal Wolf",
    "Thick-Skinned": "Stampor",
    "Up the Molehill": "Mole",
    "Way to Hell": "Magma Crawler",
    "Well Roared, Lion!": "White Liton",
    "You Got Horse Power": "Phantasmal Jade",
    "Vortex Tamer": "Vortexion",
}

const misc = {
    "His True Face": "His True Face",
    "Razing!": "Razing!",
    "The More the Merrier": "The More the Merrier",
}

module.exports = { quests, outfits, mounts, misc };
